CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o 5_1_Motivation_for_Mandatory_Copy_Elision_for_Temporaries 5_1_Motivation_for_Mandatory_Copy_Elision_for_Temporaries.cpp
	$(CC) -o 5_2_Benefit_of_Mandatory_Copy_Elision_for_Temporaries 5_2_Benefit_of_Mandatory_Copy_Elision_for_Temporaries.cpp
	$(CC) -o 5_3_and_4_Clarified_Value_Categories_and_Unmaterialized_Return_Value_Passing 5_3_and_4_Clarified_Value_Categories_and_Unmaterialized_Return_Value_Passing.cpp

.PHONY: clean
clean:
	rm 5_1_Motivation_for_Mandatory_Copy_Elision_for_Temporaries
	rm 5_2_Benefit_of_Mandatory_Copy_Elision_for_Temporaries
	rm 5_3_and_4_Clarified_Value_Categories_and_Unmaterialized_Return_Value_Passing


