CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion  -g -std=c++17

ALL: 
	$(CC) -o if_and_switch_with_Initialization if_and_switch_with_Initialization.cpp

.PHONY: clean
clean:
	rm -f if_and_switch_with_Initialization
