CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o relaxed_enum_initialization relaxed_enum_initialization.cpp

.PHONY: clean
clean:
	rm relaxed_enum_initialization
