CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o 4_Aggregate_Extensions 4_Aggregate_Extensions.cpp

.PHONY: clean
clean:
	rm 4_Aggregate_Extensions
