CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o preprocessor_condition__has_include preprocessor_condition__has_include.cpp

.PHONY: clean
clean:
	rm preprocessor_condition__has_include
