CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o hexadecimal_floating-point_literals hexadecimal_floating-point_literals.cpp

.PHONY: clean
clean:
	rm hexadecimal_floating-point_literals
