CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o exception_specifications_as_part_of_the_type exception_specifications_as_part_of_the_type.cpp

.PHONY: clean
clean:
	rm exception_specifications_as_part_of_the_type
