CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion  -g -std=c++17

ALL: 
	$(CC) -o 1_Structured_Bindings_in_Detail 1_Structured_Bindings_in_Detail.cpp
	$(CC) -o 2_Where_Structured_Bindings_can_be_Used 2_Where_Structured_Bindings_can_be_Used.cpp

.PHONY: clean
clean:
	rm -f 1_Structured_Bindings_in_Detail 2_Where_Structured_Bindings_can_be_Used

