CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o fixed_direct_list_initialization_with_auto fixed_direct_list_initialization_with_auto.cpp

.PHONY: clean
clean:
	rm fixed_direct_list_initialization_with_auto
