CC      = g++ -Wall  -Wextra  -Wpedantic -Wconversion -fsanitize=address  -g -std=c++17

ALL: 
	$(CC) -o utf-8_character_literals utf-8_character_literals.cpp

.PHONY: clean
clean:
	rm utf-8_character_literals
