CC      = g++ -Wall -Wextra  -Wpedantic -g -std=c++17
TARGET  = Any
SRC     = Any.cpp

ALL : $(TARGET)

$(TARGET): $(SRC)
	$(CC) -o $(TARGET) $(SRC)

.PHONY: clean
clean:
	rm -f $(TARGET)

